#!/usr/bin/env bash
# Concatenate site JS into a single defer-friendly bundle.
# Edit source modules under assets/js/, then re-run this script.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/assets/js/markd.bundle.js"

FILES=(
  assets/js/error-handler.js
  assets/js/utils.js
  assets/js/performance.js
  assets/js/components/config.js
  assets/js/theme.js
  assets/js/components/navbar.js
  assets/js/components/footer.js
  assets/js/components/index.js
  assets/js/translations.js
  assets/js/icons.js
  assets/js/i18n.js
  assets/js/animations.js
  assets/js/main.js
)

{
  echo "/* Mark'd site bundle — generated by scripts/build-js.sh; do not edit by hand */"
  echo "/* Source order: ${FILES[*]} */"
  for rel in "${FILES[@]}"; do
    echo ""
    echo "/* === $rel === */"
    cat "$ROOT/$rel"
    echo ""
  done
} > "$OUT"

echo "Wrote $OUT ($(wc -c < "$OUT" | tr -d ' ') bytes)"
